### ISSUE TITLE
[FEA] Minor formatting improvements for function parameters, returns

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/docs#101]
**Is your feature request related to a problem? Please describe.**
When viewing the api docs, the alignment of certain words like `Parameters, Returns, Raises` etc, varies slightly and has small variations between functions.
![image](https://user-images.githubusercontent.com/19949207/86060282-44d54e00-ba19-11ea-9792-de3aaa59c064.png)

![image](https://user-images.githubusercontent.com/19949207/86060324-5b7ba500-ba19-11ea-96f8-020e8266e475.png)

![image](https://user-images.githubusercontent.com/19949207/86060733-376c9380-ba1a-11ea-969a-64dfebe7765d.png)

Looks like the box width is determined by the longest string and then the rest of the words have whitespaces on the right based on the box width.

**Describe the solution you'd like**
Uniform alignment for the words

**Additional context**
Just a small thing I noticed while browsing api docs which doesn't impact (negatively) my experience while viewing docs.

**Comment by mike-wendt** [comment]
@ajschmidt8 @exactlyallan can you take a look to see what we can do about this?

**Comment by exactlyallan** [comment]
@ayushdg Could you give a page link where this is happening ( and what os / browser you are using ). It appears differently to me.

**Comment by ayushdg** [comment]
Hey @exactlyallan here are a few of the page links where I see this [[1]](https://docs.rapids.ai/api/cudf/nightly/api.html#cudf.core.dataframe.DataFrame.from_gpu_matrix) [[2]](https://docs.rapids.ai/api/cudf/nightly/api.html#cudf.core.dataframe.DataFrame.from_pandas) [[3]](https://docs.rapids.ai/api/cudf/nightly/api.html#cudf.core.series.Series.dt)

This is on macOS (Catalina) and is reproducible on both chrome and safari

**Comment by exactlyallan** [comment]
Closing this out - should be fixed
