### ISSUE TITLE
[BUG] cuDF Api reference tab title picks up incorrect version string

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/docs#110]
**Describe the bug**
The existing browser tab title while looking at the api reference could be improved.

**To Reproduce**
1. Go to https://docs.rapids.ai/api/cudf/stable/api.html
2. View browser tab title

**Expected behavior**
A different name such as version number 0.14, 0.15 etc

**Screenshots**
<img width="485" alt="image" src="https://user-images.githubusercontent.com/19949207/89574024-5b24b580-d7e0-11ea-920a-40bd35ad086a.png">
<img width="485" alt="image" src="https://user-images.githubusercontent.com/19949207/89574060-67107780-d7e0-11ea-9e78-3332f035ed9e.png">

In contrast, for other libraries like cuml, CuGraph the version string seems correct:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/19949207/89574468-07ff3280-d7e1-11ea-93fa-f3bc16591f36.png">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS (catalina)]
 - Browser [e.g. chrome and safari]

**Smartphone (please complete the following information):**
 - Version [Chrome: Version 84.0.4147.105 (Official Build) (64-bit)]

**Comment by mike-wendt** [comment]
@ajschmidt8 can you troubleshoot and fix before the release?

**Comment by ajschmidt8** [comment]
@ayushdg, PR open here: https://github.com/rapidsai/cudf/pull/5964

**Comment by ajschmidt8** [comment]
PR was merged. rebuilding docs now. I'll check the results when they are done.

**Comment by ajschmidt8** [comment]
fixed! https://docs.rapids.ai/api/cudf/nightly/api.html

closing issue
