### ISSUE TITLE
[DOC]Add Dask Cuda docs somewhere in promoted rapidsai docs

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/docs#129]
## Report needed documentation

**Report needed documentation**
We have great docs for [Dask Cuda](https://dask-cuda.readthedocs.io/en/latest/index.html) that is not linked to at all [in our standard docs](https://docs.rapids.ai/api).  We should link it, somewhere, in our docs.rapids.ai/api.  

A suggestion was in the `cudf` Content Section (thanks @Salonijain27 ) or part of a Content Section that includes ways of doing larger than GPU memory operations.

This doc has some of [some information and guidance not found anywhere else in the cudf docs](https://dask-cuda.readthedocs.io/en/latest/specializations.html).  This would be also helpful doing single GPU, larger than GU workloads.

@aravenel @Salonijain27 @randerzander @exactlyallan @beckernick @mike-wendt @pentschev for discussion

**Comment by pentschev** [comment]
@dillon-cullinan and I discussed this briefly yesterday, it seems we just need to add https://github.com/rapidsai/cudf/blob/branch-0.16/ci/docs/build.sh to dask-cuda and UCX-Py and we should be mostly good to go. Please correct me @dillon-cullinan if I missed something.

**Comment by charlesbluca** [comment]
Bumping this to point out that we are now exploring moving Dask-CUDA's docs to RAPIDS docs (rapidsai/dask-cuda#579).
