### ISSUE TITLE
[BUG] Broken link at mortgage-demo dataset 2 years (1 GB splits)

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/docs#14]
**Describe the bug**
Hi,

If you navigate to https://docs.rapids.ai/datasets/mortgage-data, and then press on the 2 years dataset (1 GB split), the link seems to be broken (http://rapidsai-data.s3-website.us-east-2.amazonaws.com/notebook-mortgage-data/mortgage_2000-2001_1gb.tgz)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by raydouglass** [comment]
Fixed, thanks for reporting the issue!
