### ISSUE TITLE
[DOC] Discoverability of API docs

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/docs#16]
The current documentation is super well put together from a technical standpoint.  If possible, I'd like to start a conversation about discoverability and navigation, particularly by novice users. 

As an example, the current path I take to get to the cudf API documentation is long, and non-trivial to navigate.

- Navigate to https://rapids.ai
-  Click "Docs"
-  Click "API Docs" in the upper right on the sidebar
-  Click "stable" under RAPIDS APIS / Cudf

At each of these stages I have to do a bit of mental work to find the right link.  As an extreme example consider this page:

<img width="1300" alt="Screen Shot 2019-05-03 at 11 44 25 AM" src="https://user-images.githubusercontent.com/306380/57152337-d6efb100-6d98-11e9-8de9-98705a84c480.png">

The link that I think is the most relevant today (stable or nightly for cudf) is quite small and hard to get to.  If this is indeed the most common path, then ideally it should be towards the top and also visually prominent.  It also only makes sense to developers who understand what "stable" and "nightly" mean.  Compare this to, for example the "Intended Audience" section, which comes first, and has nicely colored boxes for "community" and "developers".  While relevant, this information probably isn't the most relevant to the average user visiting this page.

If we have access to someone with extensive web UI experience (which is a challenging skill) it might be nice to get them to take a look at how things are laid out and make suggestions for where to place highly trafficked information with more prominence.  The example I gave above is just one case.  I imagine that we're mildly inefficient in a few other cases.

**Comment by mrocklin** [comment]
If the API docs are likely to be common targets, then I might suggest that we include them as larger buttons here:

<img width="1311" alt="Screen Shot 2019-05-03 at 11 57 59 AM" src="https://user-images.githubusercontent.com/306380/57152992-c04a5980-6d9a-11e9-945f-6c4de418b45e.png">

I think that arguably these links are more valuable than the contribute or github buttons that are currently there.

**Comment by mike-wendt** [comment]
Allan added a button on the first page to link to the docs so that is covered. For the UX part Allan and I will meet at the offsite to discuss this further.

**Comment by mike-wendt** [comment]
Definitely some changes made, and more on the way @mrocklin

**Comment by mike-wendt** [comment]
@mrocklin are we good to close this? #5 is coming by 0.9 with the redesigned docs

**Comment by mrocklin** [comment]
Sure.  Whatever you think is best
