### ISSUE TITLE
[DOC] outdated GDF cheatsheet at https://rapids.ai/assets/files/cheatsheet.pdf

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/docs#21]
## Report incorrect documentation
The GDF cheatsheet seems outdated. 

There are many functionalities which are already implemented, and still appear as _planned for future release_.

A few examples can be found in _subset observations_ section, where _df.head, df.tail, df.iloc_ method still appear as _planned for future release_.

Nevertheless, a full review of this document should be performed.

**Location of incorrect documentation**
https://rapids.ai/assets/files/cheatsheet.pdf

**Describe the problems or issues found in the documentation**
Outdated document

**Comment by mike-wendt** [comment]
@JohnZed @robocopnixon @kkraus14 any thoughts on this? I'm not sure if there is an update to this or not

**Comment by robocopnixon** [comment]
I can a look with Mike B, but we usually have someone help make it look good so I'm not sure what the turn around will be.

**Comment by miguelangel** [comment]
Hi!

It looks like the details are already in the cheatsheet, but hidden by a layer. You only need to remove the layer to have the cheatsheet updated.

Hope it helps!

Miguel

**Comment by miguelangel** [comment]
@robocopnixon (fyi)

**Comment by JohnZed** [comment]
Sorry, I think this is the first time I've seen that cheatsheet. Probably Keith would know best.

**Comment by miguelangel** [comment]
Hi,

I have tried to amend the current version of the file to cover the functionality which is available now.

In case it might be reviewed by someone.

Regards,
Miguel
[cheatsheet.pdf](https://github.com/rapidsai/docs/files/3720914/cheatsheet.pdf)

**Comment by exactlyallan** [comment]
bump?
