### ISSUE TITLE
[DOC] Fannie Mae datasets not included in rapidsai/rapidsai Docker Image

### ISSUE THREAD

**Issue by rrpelgrim** [rapidsai/docs#213]
## Report incorrect documentation

**Location of incorrect documentation**
https://docs.rapids.ai/datasets/mortgage-data

**Describe the problems or issues found in the documentation**
The docs state that the notebooks in the Docker image work with the Fannie Mae mortgage datasets, but they don't.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:
- pulled and run Docker image rapidsai/rapidsai
- accessed notebooks in Jupyerlab through localport 8888
- gone through all of the notebooks and found none using the Fannie Mae mortgage datasets listed on the page linked at the top of this issue (note: 1 cuxfilter notebook does use mortgage data, but that is not one of the datasets listed on the linked page and does not help me understand how to properly import the data)

**Suggested fix for documentation**
- update docs to correct 
- ideally: include notebooks in Docker image that do use the Fannie Mae datasets

**Comment by exactlyallan** [comment]
I believe the demo has been removed.
