### ISSUE TITLE
[QST] Is blazingsql no longer part of RAPIDS ?

### ISSUE THREAD

**Issue by igorbb** [rapidsai/docs#243]
**What is your question?**
Is blazingsql no longer part of RAPIDS ?

The previous [getting started  page  ](https://rapids.ai/start.html#get-rapids) release selector used to install blazingsql when installing all packages.
The current one seems to install dask-sql but it does not install blazingsql. 
This means blazingsql is no longer supported or a part of RAPIDS ?

**Comment by aravenel** [comment]
Hi,

BlazingSQL is no longer being actively maintained, and so has been removed from the RAPIDS install options. Dask-SQL provides very similar functionality and performance, and has replaced BlazingSQL as an install option.
