### ISSUE TITLE
[BUG]Docs rendering sometimes combines variable name and first data type, causing variable name confusion

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/docs#28]
**Describe the bug**
Throughout the entirety of docs, in many methods, there are no spaces between the variable name and the data type.  This is very confusing because the docs' rendering shows users incorrect variable names.  this affects cuml, cudf, and other areas of docs in both stable and nightlies - probably others.

**Behavior**
the docs should read like this: 
`alpha: float (default = 0.0001)`

but instead read like this:
`tolfloat (default = 1e-3)`

**Screenshots**
![image](https://user-images.githubusercontent.com/46935140/60136609-7c9c1c80-9759-11e9-97b5-1f622ebe3219.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows for me, but others across other systems confirm (linux, osx)]
 - Browser chrome for me

**Proposed solution**
@cjnolet and I debugged the instances where this happened.  He discovered that you can't gave space between the variable name and the ':'.  e.g.:
* Good : `alpha: float (default = 0.0001)` = `alpha: float (default = 0.0001)`
* Bad: `alpha float (default = 0.0001)` = `alphafloat (default = 0.0001)` 
* Bad: `alpha : float (default = 0.0001)` = `alphafloat (default = 0.0001)` 

@dantegd @JohnZed and @cjnolet, references a discussion you had last week?

**Comment by JohnZed** [comment]
Hi, @taureandyernv - having a space is the correct approach according to the numpydoc standard, which we follow: https://numpydoc.readthedocs.io/en/latest/format.html#sections. So you should do `alpha : float`

There is a bug in Sphinx that is causing these to render incorrectly. I merged a fix into cuML that fixes the rendering issue: https://github.com/rapidsai/cuml/pull/759. You'll see that cuML nightlies are now correct: https://docs.rapids.ai/api/cuml/nightly/

Dillon is planning to roll this out to the whole codebase.  Thanks!

**Comment by mike-wendt** [comment]
rapidsai/ops#199 is working on this, will close this in favor of the ops issue
