### ISSUE TITLE
[BUG] Dark mode font color is too light

### ISSUE THREAD

**Issue by harrism** [rapidsai/docs#284]
**Describe the bug**
This appears in the 22.08 nightly docs, but not in the stable 22.06 docs, so we should get it fixed before 22.08 release.

In dark mode, the paragraph font color is light grey on white, which is hard to read.

![image](https://user-images.githubusercontent.com/783069/181398963-0b7de784-308d-4a60-9718-a9cc91e634b7.png)

Here's the same text in light mode, or in the stable 22.06 docs:
![image](https://user-images.githubusercontent.com/783069/181399209-6060c2e5-de48-41c2-b166-5e8309889df8.png)

If you are on a mac with dark mode set, this is the default, which is bad. You can cycle through modes on the site with this button (left one): 
![image](https://user-images.githubusercontent.com/783069/181399067-b31dfe64-0913-487c-95bb-f885a455b568.png)

Note that another bug is that there is no hover hint text on that button. But you can see what it does if you turn on the javascript console, where it prints: 

```
Changed to light mode using the light theme. pydata-sphinx-theme.js:32:63449
Changed to dark mode using the dark theme. pydata-sphinx-theme.js:32:63449
Changed to auto mode using the dark theme.
```

Verified this on Firefox and Chrome on Mac and Window.

**Comment by galipremsagar** [comment]
I'm looking into this.
