### ISSUE TITLE
[BUG] doc.rapids.ai API reference websites scrolling doesn't work in iOS devices (iOS <=12)

### ISSUE THREAD

**Issue by dantegd** [rapidsai/docs#29]
**Describe the bug**
API reference websites in doc.rapids.ai cannot be scrolled in iOS devices (tested in iPhone X, iPad Pro). When trying to scroll only the upper bar moves. 

**To Reproduce**
Open https://docs.rapids.ai/api/cudf/stable/ in an iPhone or iPad and try to scroll. 

**Expected behavior**
Websites should be scrollable (and ideal responsive) on iOS devices. 

**Smartphone (please complete the following information):**
 - Device: iPhone X, iPhone XS Max, and iPad Pro 11''
 - OS: iOS 12.3.1
 - Browser Safari

Tagging @miguelangel that found this originally

**Comment by mike-wendt** [comment]
Will look at but this will most likely not make the 0.8 release

**Comment by mike-wendt** [comment]
This will be release with 0.13, changes are done, we are waiting on the release to publish.
