### ISSUE TITLE
[BUG] Very different results between umap package and cuml.umap

### ISSUE THREAD

**Issue by hectorpatino** [rapidsai/docs#324]
**Describe the bug**
I have significant difference in results of umap package and cuml.umap running on kaggle.

**To Reproduce**
1. Go to ['This kaggle notebook'](https://www.kaggle.com/code/hectorpatio/cpu-umap-vs-gpu-umap/settings)
2. Click copy and edit.
3. Click on Accelator GPU T4 x2
4. Execute the code.
5. Check the difference

**Expected behavior**
The results of the algorithm are very different. I expected different results, but the vary too much

**Additional context**
This is executed in kaggle

**Comment by exactlyallan** [comment]
@hectorpatino if this is still an issue it should be raised here: https://github.com/rapidsai/cuml/issues
