### ISSUE TITLE
[FEA] Add NGC docker pull instructions

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/docs#35]
**Is your feature request related to a problem? Please describe.**
Hi!
I have just noticed that install instructions for NGC containers are missing at rapids.ai homepage:
I think we might promote NGC by adding NGC install instructions too.
**Describe the solution you'd like**
Docker pull instructions referring to NGC container registry.

**Describe alternatives you've considered**
None.

**Additional context**
https://rapids.ai/start.html#get-rapids

**Comment by exactlyallan** [comment]
@beckernick is this still relevant?

**Comment by miguelusque** [comment]
Hi @exactlyallan , @beckernick , this is already solved. Closing it now...
