### ISSUE TITLE
[BUG] API Ref Links In Sidebar of cuGraph Don't Move to Correct Position

### ISSUE THREAD

**Issue by BartleyR** [rapidsai/docs#36]
**Describe the bug**
When clicking on a link in the sidebar of the cuGraph docs site, the result doesn't go to the correct location in the main docs page.

**To Reproduce**

1. Go here: https://docs.rapids.ai/api/cugraph/stable/
2. Click on Louvain
3. The result goes to PageRank, not Louvain

**Expected behavior**
Link should move to Louvain on the page

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Safari (v 12.12)
 - Browser: Chrome (v 75.0.3770.142)
 - Browser: Firefox (v 68.0.1)

**Smartphone (please complete the following information):**
Did not test on mobile

**Comment by mike-wendt** [comment]
This will be release with 0.13, changes are done, we are waiting on the release to publish.
