### ISSUE TITLE
[DOC] Specify RAFT burndow / code freeze schedule

### ISSUE THREAD

**Issue by tfeher** [rapidsai/docs#364]
## Report needed documentation

It is planned to bring the raft burndown / code freeze date forward to be at the same time as cudf, rmm and others. 

The maintainers docs at https://docs.rapids.ai/maintainers shows the release schedule, but currently does not list raft among the libraries that have early code freeze.

Once the earlier schedule for raft is confirmed, then please specify explicitly raft among the other libraries with early code freeze.

**Comment by jarmak-nv** [comment]
#378 resolved this, closing!
