### ISSUE TITLE
[DOC] Docker Command To Run the Container Uses Deprecated Flag

### ISSUE THREAD

**Issue by necromuralist** [rapidsai/docs#38]
## Report incorrect documentation

**Location of incorrect documentation**
https://rapids.ai/start.html

**Describe the problems or issues found in the documentation**
![rapids](https://user-images.githubusercontent.com/3393973/62825851-f4d26c00-bb66-11e9-8dc3-128eded3fa3e.png)

The line:

```
docker run --runtime=nvidia --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 \
rapidsai/rapidsai:0.8-cuda10.0-runtime-ubuntu18.04-gcc7-py3.7
```

Uses the ``--runtime=nvidia`` flag which is for the deprecated `nvidia-docker2` package and raises an _Unkown runtime_ error if you are instead using the  `nvidia-container-toolkit` (https://github.com/NVIDIA/nvidia-docker).

**Steps taken to verify documentation is incorrect**
I ran the command with the flag and it quit with an Unknown runtime error. I downgraded my docker package back to one compatible with nvidia-docker2 (it wouldn't install with my Ubuntu 19.04 version) and installed nvidia-docker2 and it ran without error. Then I removed nvidia-docker2 and reinstalled docker-ce  19.03 and the nvidia-container-toolkit and re-ran the command without the flag and it launched the container without error.

**Suggested fix for documentation**

Remove the flag but note that users of the `nvidia-docker2` package might need to use it if they are using a version of docker prior to 19.03.

**Comment by mike-wendt** [comment]
This has been updated, please reopen if necessary
