### ISSUE TITLE
[DOC] pip requirements are unclear

### ISSUE THREAD

**Issue by bdice** [rapidsai/docs#380]
## Report incorrect documentation

**Location of incorrect documentation**
https://docs.rapids.ai/install#pip-install

**Describe the problems or issues found in the documentation**

I want to do some revisions of the pip requirements, which I have helped several users with recently. See: https://github.com/rapidsai/cudf/issues/13233#issuecomment-1524535099 for an example and more details. We can do this in this PR #377 or a follow-up PR. For the moment, I am going to list two clarifications that are needed:

- Users need a **CUDA 11 toolkit** to use pip packages. CUDA 12 will fail.
  - We need to fix our docs where it says "CUDA >= 11.2, with at least the v460.27.03 driver" because that implies CUDA 12 is valid. It is not, for pip.
- We need to increase emphasis (even more) on the WSL side, to **ensure that CUDA drivers are not installed in WSL**; only `cuda-toolkit` and not `cuda`. We already point to a guide that explains this and we say in the link text, "[install the CUDA Toolkit without drivers](https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_local) into the WSL2 instance."
  - I think we can spell out exactly what this means in the requirements step: we should say "Execute `sudo apt-get -y install cuda-toolkit` and not `sudo apt-get -y install cuda` to avoid installing a driver into WSL2."

**Comment by jarmak-nv** [comment]
Point 1 - totally agree, we also probably should also note that it's okay for the Windows host to have CUDA 12, but not the Linux OS.

Point 2 - just want to get clarification, is your intention something like:

-----
WSL and pip
### Prepare your WSL Environment
- Ensure you have the [latest NVIDIA Drivers](https://www.nvidia.com/download/index.aspx) on the Windows host.
- Install WSL2 and the Ubuntu 22.04 package [using Microsoft’s instructions](https://docs.microsoft.com/en-us/windows/wsl/install).
- Log in to the WSL2 Ubuntu 22.04 instance

### Prepare CUDA inside your Ubuntu 22.04 WSL Instance
! You **must** install CUDA as defined below !
- Follow [this helpful developer guide](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#cuda-support-for-wsl2) and then [install the CUDA Toolkit without drivers](https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_local) into the Ubuntu WSL2 instance. Copy and paste the following commands to install the driver-less CUDA inside your Ubuntu WSL2 Instance:
    - (pretend this is formatted as code)
    - wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin
    - sudo mv cuda-wsl-ubuntu.pin /etc/apt/preferences.d/cuda-repository-pin-600
    - wget https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda-repo-wsl-ubuntu-11-8-local_11.8.0-1_amd64.deb
    - sudo dpkg -i cuda-repo-wsl-ubuntu-11-8-local_11.8.0-1_amd64.deb
    - sudo cp /var/cuda-repo-wsl-ubuntu-11-8-local/cuda-*-keyring.gpg /usr/share/keyrings/
    - sudo apt-get update
    - sudo apt-get -y install cuda

### Installing RAPIDS
- Install RAPIDS pip packages on the WSL2 Ubuntu Instance using the [pip instructions](https://docs.rapids.ai/install#pip-install).
- Run this code to check that the RAPIDS installation is working: [code]

---

All these changes, and specificities for WSL make me wonder if it should be its own page entirely, and references stripped from this page. Maybe too much of a change.

**Comment by exactlyallan** [comment]
Should we close this?

**Comment by bdice** [comment]
@exactlyallan I'd still like to address this:

> I think we can spell out exactly what this means in the requirements step: we should say "Execute `sudo apt-get -y install cuda-toolkit` and not `sudo apt-get -y install cuda` to avoid installing a driver into WSL2."

I'll file a small PR.
