### ISSUE TITLE
[BUG] Anchor link is not working for WSL2 install instructions

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/docs#382]
**Describe the bug**
The current WSL2 install instruction link does not navigates to the correct section.

The current link is
[https://docs.rapids.ai/install?_gl=1*rzv7ha*_ga*MTkzOTY2MjAxMy4xNjgyNTk1OTU5*_ga_RKXFW6CM42*MTY4MzAxNzE0OS4yLjAuMTY4MzAxNzE0OS42MC4wLjA.#wsl2](https://docs.rapids.ai/install?_gl=1*rzv7ha*_ga*MTkzOTY2MjAxMy4xNjgyNTk1OTU5*_ga_RKXFW6CM42*MTY4MzAxNzE0OS4yLjAuMTY4MzAxNzE0OS42MC4wLjA.#wsl2)
while I think it should be:
[https://docs.rapids.ai/install?_gl=1*zwmw1b*_ga*MTkzOTY2MjAxMy4xNjgyNTk1OTU5*_ga_RKXFW6CM42*MTY4MzAxNzE0OS4yLjAuMTY4MzAxNzE0OS42MC4wLjA.#WSL2](https://docs.rapids.ai/install?_gl=1*zwmw1b*_ga*MTkzOTY2MjAxMy4xNjgyNTk1OTU5*_ga_RKXFW6CM42*MTY4MzAxNzE0OS4yLjAuMTY4MzAxNzE0OS42MC4wLjA.#WSL2)

In addition to the above, the section 'Do I need an advanced install?' just below the Docker and WSL-2 instructions refer to Docker and WSL-2 instructions in the following paragraph:

> If you want to use Docker, WSL2, have an uncommon OS, hardware configuration, environment, or need specific versions such as CUDA 11.5 or Python 3.8 then you should use the installation selector in our Advanced Installations Page 

I would remove the references to Docker and WSL-2, considering they already have a section above pointing to the right place. I leave it as follows:

> If you have an uncommon OS, hardware configuration, environment, or need specific versions such as CUDA 11.5 or Python 3.8 then you should use the installation selector in our Advanced Installations Page 

Hope it helps!

Miguel

**To Reproduce**
1. Go to ['https://rapids.ai/#quick-start'](https://rapids.ai/#quick-start)
2. Click on 'WSL2 installation instructions'

**Expected behavior**
Navigate to the right WSL2 section

**Comment by exactlyallan** [comment]
I keep forgetting that anchors are case sensitive...

**Comment by jarmak-nv** [comment]
Confirmed the anchor is now working with #377 merged!

@miguelusque please let us know if the updated install page clears things up - thanks!
