### ISSUE TITLE
Update docs for CUDA 12 pip wheel release

### ISSUE THREAD

**Issue by vyasr** [rapidsai/docs#386]
The core RAPIDS packages that build wheels (rmm, cudf, raft, cuml, cugraph, cuopt, ucx-py) are now also building wheels with CUDA 12 support. We plan to release these packages in 23.06. The documentation needs to be updated to reflect that release.

CC @exactlyallan @ajschmidt8

**Comment by jarmak-nv** [comment]
This is done with #394 and #396 :tada:
