### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jglev** [rapidsai/docs#392]
**Describe the bug**
https://pypi.nvidia.com/ is giving an "Access Denied" error, preventing a user from following the RAPIDS installation instructions.

**To Reproduce**
1. Go to https://docs.rapids.ai/install.
2. Follow the pip installation instructions, which includes `--extra-index-url=https://pypi.nvidia.com` (e.g., `pip install cudf-cu11 --extra-index-url=https://pypi.nvidia.com`). Alternatively, visit https://pypi.nvidia.com in a web browser.
4. See error.

**Expected behavior**
https://pypi.nvidia.com should not return an "Access Denied" error.

**Screenshots**
Shell output:
```sh
pip install cudf-cu11 --extra-index-url=https://pypi.nvidia.com

Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting cudf-cu11
  Using cached cudf_cu11-23.4.1.tar.gz (6.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/rr/8b1h0vgs3mv5dl3rz2rtr2600000gr/T/pip-install-lcd7wd0l/cudf-cu11_cbe9c763a56044ea803b81689ea3a4cd/setup.py", line 137, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.

      This package can be installed as:
      ```
      $ pip install --extra-index-url https://pypi.nvidia.com cudf_cu11
      ```
      ###########################################################################################

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Screenshot of https://pypi.nvidia.com/:
![image](https://github.com/rapidsai/docs/assets/3667562/fa7855be-1b3c-4d76-abcb-1bb09a1553b5)

**Desktop (please complete the following information):**
 - OS: (Occurs across two systems: Ubuntu 22.04.2 LTS; MacOS Ventura 13.3.1 (a), Apple M2 Pro chip)
 - Browser: Chrome Version 113.0.5672.92 (Official Build) (arm64)
 - Version: N/A

**Additional context**
This does not seem to be a temporary issue -- https://pypi.nvidia.com/ has been displaying this Access Denied error since at least 2023-05-13.

**Comment by jarmak-nv** [comment]
Hi @jglev thanks for reporting! The website failure is expected, it's not pretty but it's only designed to be accessed through pip.

I see you're on an Apple M2 machine, is that the machine you're attempting to install cuDF into? RAPIDS libraries require NVIDIA GPUs so just want to make sure you're meeting that requirement before digging deeper.

Thanks!

**Comment by jglev** [comment]
@jarmak-nv, thank you for your response -- and for all of your work on RAPIDS!

I'm sorry my report was unclear! To confirm, the machine I'm trying to install on is an Ubuntu server separate from my Apple M2 machine (I just had also tried installing on the Apple machine to see whether there might be any network issues that would explain the behavior). Running `nvidia-smi` on the server shows a CUDA Version of 12.1. I get the following output when trying to install `cudf-cu12` on the server:

```sh
$ pip install --force --extra-index-url=https://pypi.nvidia.com cudf-cu12
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
ERROR: Could not find a version that satisfies the requirement cudf-cu12 (from versions: none)
ERROR: No matching distribution found for cudf-cu12
```

**Comment by jglev** [comment]
Have I misunderstood, such that CUDA 12 isn't supported? I just realized that `pip install cudf-cu11 --extra-index-url=https://pypi.nvidia.com` does work on the server. I apologize for this report being less clear than I meant for it to be!

**Comment by jarmak-nv** [comment]
Hey @jglev with 23.06 being released, we now have CUDA 12 wheels for pip!

Check out the selector and install page for specific supported installations:
https://docs.rapids.ai/install#selector

**Comment by bdice** [comment]
Looks like this is handled for now -- thanks for filing this issue, and feel free to reopen if you have more questions.

In the meantime, if you need to browse the NVIDIA Python Package Index, you might try https://pypi.nvidia.com/index.html -- but note that this page isn't complete at the moment due to some issues beyond RAPIDS' control.
