### ISSUE TITLE
[FEA] Add cuSpatial to PiP Release Selector

### ISSUE THREAD

**Issue by isVoid** [rapidsai/docs#395]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish I could use the docs site to do [...]

cuspatial 23.06 release adds PiP installation support to cuspatial: https://github.com/rapidsai/cuspatial/pull/1148 (pending final approval). Once merged, we would like cuspatial to show up on the release selector PiP section, and be mentioned in the "pip" section below.

**Comment by exactlyallan** [comment]
Also a request to add RMM - https://github.com/rapidsai/rapids.ai/issues/320

**Comment by bdice** [comment]
Closed by #394. cuSpatial is now in the release selector.
