### ISSUE TITLE
[DOC] Redirect library API docs root

### ISSUE THREAD

**Issue by bdice** [rapidsai/docs#400]
Currently https://docs.rapids.ai/api/cudf/ gives an error and redirects to https://docs.rapids.ai/api. We should make it redirect to https://docs.rapids.ai/api/cudf/stable/ or https://docs.rapids.ai/api/cudf/nightly/. (Same for all RAPIDS repos.)

**Comment by bdice** [comment]
Note: ReadTheDocs recently adopted a similar change so that (for example) https://setuptools.pypa.io/en/ redirects to https://setuptools.pypa.io/en/latest/.

**Comment by exactlyallan** [comment]
I think we have this plugin installed - https://github.com/jekyll/jekyll-redirect-from
Or we could consolidate with what @ajschmidt8 has setup for redirects using netlify. 
In a few months, this issue will go away via: https://github.com/orgs/rapidsai/projects/73?pane=issue&itemId=28388936

**Comment by ajschmidt8** [comment]
PR here: https://github.com/rapidsai/docs/pull/401

**Comment by ajschmidt8** [comment]
Looks like this is resolved. You can test the links below:

- https://docs.rapids.ai/api/libcudf
- https://docs.rapids.ai/api/cudf
- https://docs.rapids.ai/api/cuml
- https://docs.rapids.ai/api/libcuml

@bdice, feel free to close this after you've confirmed everything.

**Comment by bdice** [comment]
Looks good to me!
