### ISSUE TITLE
How to supplement the installation of cuml

### ISSUE THREAD

**Issue by lingzisanren** [rapidsai/docs#489]
Dear Publisher:
Greetings! I have installed rapids-23.12, but I realized that I forgot to install cuml, so I need to install cuml additionally.
Looking forward to your reply!

**Comment by bdice** [comment]
Hi @lingzisanren, the install selector on https://docs.rapids.ai/install has example conda commands like this:
```
conda create --solver=libmamba -n rapids-24.02 -c rapidsai -c conda-forge -c nvidia  \
    rapids=24.02 python=3.10 cuda-version=12.0
```

If you install the `rapids` metapackage, that will include the following list of packages and their dependencies:
- cucim
- cudf
- cugraph
- cuml
- cuproj
- cupy
- cuspatial
- custreamz
- cuxfilter
- dask-cuda
- libcugraph_etl
- pylibcugraph
- rapids-xgboost
- rmm

If you install with pip, there is no `rapids` metapackage. You must install each package individually like this:

```
pip install \
    --extra-index-url=https://pypi.nvidia.com \
    cudf-cu12==24.2.* dask-cudf-cu12==24.2.* cuml-cu12==24.2.* \
    cugraph-cu12==24.2.* cuspatial-cu12==24.2.* cuproj-cu12==24.2.* \
    cuxfilter-cu12==24.2.* cucim-cu12==24.2.* pylibraft-cu12==24.2.* \
    raft-dask-cu12==24.2.*
```

Hope that helps. If you have further questions please feel free to reopen.
