### ISSUE TITLE
[FEA] Unable to get a link to a particular page

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/docs#5]
Due to the use of frames its difficult to get URLs for particular pages.  This is important when pointing people to particular documentation pages.

**Comment by mrocklin** [comment]
I tried linking to a doc page from an issue today and couldn't figure out how to do it.  Any suggestions?

**Comment by raydouglass** [comment]
The non-apidocs pages have unique URLs. In the apidocs, if you hover over a function you can right click the "link" symbol on the next and copy the hyperlink. That will be a URL directly to that function.

It's not perfect though since the link won't have the sidebars.

**Comment by mrocklin** [comment]
I was trying to get to this page: https://rapidsai.github.io/projects/cudf/en/0.7.0/dask-cudf.html

I had to look at page source to get there.

**Comment by mike-wendt** [comment]
The best thing to do is to right-click and copy a link to share. This is the best way to do this at the moment. Allan and I will brainstorm ways to overcome this, but expect them in 0.9 or later.

**Comment by mike-wendt** [comment]
This will be release with 0.13
