### ISSUE TITLE
[DOC] Add temporary redirect for https://rapids.ai/nx-cugraph

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/docs#545]
## Report needed documentation

**Report needed documentation**
We're planning on having a landing page for nx-cugraph modeled after https://rapids.ai/cudf-pandas.  In the short term before this is complete, we need to use the URL in docs and metadata and would ideally not want that URL result in a 404.

**Describe the documentation you'd like**
This request is to have https://rapids.ai/nx-cugraph redirect to https://github.com/rapidsai/cugraph/tree/HEAD/python/nx-cugraph . The redirect will only be in place until the nx-cugraph landing page is created.

**Steps taken to search for needed documentation**
n/a

cc @exactlyallan @ajschmidt8

**Comment by ajschmidt8** [comment]
You can accomplish this by adding a line in the file below. The first column is "the path that should redirect" and the second column is "where it should redirect to".

- https://github.com/rapidsai/rapids.ai/blob/main/_redirects

**Comment by rlratzel** [comment]
Thanks @ajschmidt8 .  I've submitted [this PR](https://github.com/rapidsai/rapids.ai/pull/408).

**Comment by ajschmidt8** [comment]
PR is approved, merged, and deployed. @rlratzel, feel free to close this issue after you verify everything is working correctly.

You can check these links:

- https://rapids.ai/nx-cugraph
- https://rapids.ai/nx-cugraph/

**Comment by rlratzel** [comment]
The above PR was merged and I verified the redirect works.
