### ISSUE TITLE
[DOC] Missing dropdown element with 0.6 version

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/docs#6]
## Report incorrect documentation
Hi,

I have reached to this page: https://docs.rapids.ai/api/cudf/stable/

Then, I use the dropdown on the top right side of the page to read the 0.5 API. After that, I cannot return to the current version (0.6) without leaving that page.

I think it is missing an element in the dropdown, which links to the latest version.

![image](https://user-images.githubusercontent.com/26169771/55389882-0313da00-552e-11e9-966e-c754ae4b08b4.png)

Finally, there is also a link to nvStrings v0.2 element in the dropdown, which I am not sure if it should be there.

**Location of incorrect documentation**
Provide links and line numbers if applicable.

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by raydouglass** [comment]
@miguelangel You can navigate back to the stable or v0.6 by clicking on `cuDF` in the Stable section.

The dropdown is only for legacy versions.

**Comment by miguelangel** [comment]
Hi @raydouglass,

Thank you for the tip.

Would you like me to close the issue, or are you planning to add the latest version to the dropdown?

As you can figure out, I did not figure out your solution. I think that, maybe, others might face the same doubt.

Regards,
Miguel

**Comment by mike-wendt** [comment]
This will be release with 0.13, changes are done, we are waiting on the release to publish.
