### ISSUE TITLE
[BUG] customize_doc.py is oblivious to repo-local Doxygen CSS customizations

### ISSUE THREAD

**Issue by harrism** [rapidsai/docs#91]
**Describe the bug**

We recently merged two libcudf doc PRs that modify the display of libcudf rendered doxygen docs using custom CSS. The docs look great locally, but on https://rapids.ai the new CSS is lost, because `customize_doc.py` assumes there is no local CSS and so it doesn't copy the CSS files and it overwrites all CSS html tags in the `<head>` block.

These are the PRs:
rapidsai/cudf#5349
rapidsai/cudf#5429

**Expected behavior**
Copy any local CSS and don't overwrite custom CSS tags in the `<head>`.

**Comment by ajschmidt8** [comment]
looks like i'm seeing the new styles on https://docs.rapids.ai/api/libcudf/nightly/classcudf_1_1column__view.html after the docs rebuilt. closing this issue. feel free to reopen if anything still looks off.
